version: '3.8'

volumes:
  media_server:
  media_cache:

networks:
  media_network:
  
services:
  mediahost:
    image: jellyfin/jellyfin
    container_name: mediahost
    user: 1000:1000
    ports:
      - '7259:8096'
    volumes:
      - media_server:/config
      - media_cache:/cache
      - /mnt/media:/media2:ro
    restart: 'unless-stopped'
    networks:
      - media_network
    labels:
      - "traefil.enable=true"
