version: "3.8"

volumes:
  cluster_log: {}
  cluster_data:
  config_secure:

networks:
  manager_network:

services:
  grafana:
    image: grafana/grafana-enterprise
    ports:
     - '6285:3000'
    volumes:
      - cluster_log:/var/lib/grafana
    networks:
      - manager_network   

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    volumes:
      - cluster_data:/prometheus
      - config_secure:/etc/prometheus:ro
    networks:
      - manager_network

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    deploy:
      mode: global
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - manager_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor-arm64:v0.47.2
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - '9240:8080'
    networks:
      - manager_network
      
